### ISSUE TITLE
ESV:0x73の状態変化時通知の値がDETAILsに溜まる。

### ISSUE THREAD

**Issue by ryoma3111** [Hiroshi-Sugimura/echonet-lite.js#10]
### もう一つ改良をお願いします。
#9 EL.parseBytes()での複数OPCの場合

エアコンに対象プロパティのESV:63状態変化通知要求を送信した後、状態変化時の通知ESV:73を受信しました。
データのプロパティが多く上記問題と同じようにDETAILsに溜まります。
主な利用目的はエアコンの赤外線リモコンの設定取得、エアコンの室内温度取得です。

### ESV:73 状態変化時通知 RAWデータ
`[16,129,0,36,1,48,1,14,240,1,115,3,176,1,64,241,2,48,82,250,80,237,0,0,0,5,0,0,32,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,52,0,0,0,0,0,0,0,0,0,0,1,0,90,0,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,0,56,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]`

### EL.parseBytes()適用後
`{"EHD":"1081","TID":"0024","SEOJ":"013001","DEOJ":"0ef001","EDATA":"7303b00140f1023052fa50ed00000005000020000000000000000000000000000001000000340000000000000000000001005a000000000000000000ff000000000000000038000100000000000000000000000000000000000000","ESV":"73","OPC":"03","DETAIL":"b00140f1023052fa50ed00000005000020000000000000000000000000000001000000340000000000000000000001005a000000000000000000ff000000000000000038000100000000000000000000000000000000000000","DETAILs":{"b0":"40","f1":"3052","fa":"ed00000005000020000000000000000000000000000001000000340000000000000000000001005a000000000000000000ff000000000000000038000100000000000000000000000000000000000000"}}`

**Comment by Hiroshi-Sugimura** [comment]
調査します

**Comment by Hiroshi-Sugimura** [comment]
すみません，問題がよくわかりませんでした。

EDATA = 7303b00140f1023052fa50ed00000005000020000000000000000000000000000001000000340000000000000000000001005a000000000000000000ff000000000000000038000100000000000000000000000000000000000000

とのことなので，

EPC = 73
OPC = 03　（各EPC,EDTのセットがOPC=3個ある）

"b0":"40"
"f1":"3052"
"fa":"ed00000005000020000000000000000000000000000001000000340000000000000000000001005a000000000000000000ff000000000000000038000100000000000000000000000000000000000000"

は合っているような気がしました。
期待している正解例がいただければ，もう少し調査が進められると思います。

**Comment by Hiroshi-Sugimura** [comment]
状況再現がうまくできませんでしたが、0x73ではないところで、受信時のデータ蓄積方法を変えたのでもしかしたら治っているかもしれません。また同様の問題が出るようでしたら改めてissueとしていただけますか
