### ISSUE TITLE
EL.sendOPC1()のTIDについて

### ISSUE THREAD

**Issue by acknpop** [Hiroshi-Sugimura/echonet-lite.js#12]
picogwを立ち上げて、echonet-lite.jsのDevice Demoの実装に対してGet要求を発行したところタイムアウトになるようです。
ECHONET-Liteの規格書の３．２．２ Transaction ID（TID）は

> ECHONET Lite 通信において、要求送信側が応答受信時に、自己が送信した要求と受信した応答をひも付けするためのパラメータである。応答送信側は、要求メッセージに含まれる値と同じ値を格納すること。プロパティ値通知など、応答受信を必要としないメッセージのTID の値については特に規定しない。

となっていますが、Device Demoのように応答にEL.sendOPC1()を用いると要求送信側とTIDが異なる場合に上記を満たさないように思いますがいかがでしょうか？
要求送信側のTIDをうまく設定してsendする方法をご教示いただければ幸いです。

**Comment by Hiroshi-Sugimura** [comment]
たしかにDevice Demoでは良くない例になっていますね。修正します。
また、Device側のReplyとして要求送信側のTIDをうまく設定してsendする方法については
これから検討してみます。

現在のバージョンではsendBase、sendArray、sendStringはTIDを計算しないので、
自分でTIDを計算してそちらを使うことで対応可能と思います。

- Bufferの時
EL.sendBase = function( ip, buffer )

- 配列の時
EL.sendArray = function( ip, array )

- E文字列タイプ
EL.sendString = function( ip, string )

どうもありがとうございます。

**Comment by Hiroshi-Sugimura** [comment]
いや、上記３APIもダメですね。バグですね。修正します。

**Comment by acknpop** [comment]
ご確認ありがとうございました。
修正、お待ちしてます。

**Comment by Hiroshi-Sugimura** [comment]
修正し、Ver. 2.7.0としてpublishしました。
- replyOPC1を追加しました。
- ライブラリの中でやっている自動返信でのTIDの設定バグを修正しました。
- Device demoを修正しました。

**Comment by acknpop** [comment]
早速のご対応ありがとうございました。
なるほど応答用の関数を別にされたんですね。
当方でも動作確認ＯＫでした。
