### ISSUE TITLE
Module not found: Error: Can't resolve 'dgram' in 'D:\xxx\node_modules\echonet-lite'

### ISSUE THREAD

**Issue by christaotaoz** [Hiroshi-Sugimura/echonet-lite.js#13]
### **1.** 私の環境：
- echonet-lite: 2.14.2
- node:16.13.2
- webpack: 5.5.1
- webpack-cli: 4.2.0

### **2.** 間違った説明：
npm i echonet-lite を実行して echonet-lite モジュールを追加しました. webpack コマンドを実行してパッケージ化すると、dgram パッケージがエラーを検出できないと報告されます. 確認したところ、dgram は廃止されており、npm i  dgramからインストールできません.パッケージングエラーを回避する方法を教えてください.具体的なエラーは次のとおりです
![image](https://user-images.githubusercontent.com/43243025/217142861-96d23407-2033-4322-ab08-ff43bc105799.png)

**Comment by Hiroshi-Sugimura** [comment]
dgramの機能はNode.js v17あたりで、最初からライブラリに入るようになったと思いますのでこれを使うとよいと思います。
Node v17の変更に伴って、NPMのdgramは削除されています。

詳しくは下記が参考になると思います。
https://qiita.com/youtoy/items/385feead64ff905e9f76

それ以上に問題があればまた教えてください。
