### ISSUE TITLE
OPC != 1 の時の受信処理でのEDTが積算されていしまう不具合

### ISSUE THREAD

**Issue by taharactrl** [Hiroshi-Sugimura/echonet-lite.js#5]
複数のEPCを取得しようとした際にOPC != 1 でのparseDetailsの処理に不具合があります。
以下のパッチの適用をお願いできないでしょうか。

    diff --git a/index.js b/index.js
    index 5490ee2..39d9e10 100644
    --- a/index.js
    +++ b/index.js
    @@ -170,10 +170,19 @@ EL.parseDetail = function( opc, str ) {
                    var edt = [];
                    var array = EL.toHexArray( str );  // edts
     
    +               // OPCの型変換（HEX→10進）
    +               if(typeof opc === 'string'){
    +                       opc = parseInt(opc, 16);
    +               }
    +
                    // OPCループ
                    for( var i = 0; i< opc; i += 1 ) {
                            // EPC（機能）
                            epc = array[now];
    +
    +                       // edtの初期化（OPC != 1 用）
    +                       edt = [];
    +
                            now++;
     
                            // PDC（EDTのバイト数）

**Comment by Hiroshi-Sugimura** [comment]
修正しました。
