### ISSUE TITLE
DeprecationWarning for Buffer()

### ISSUE THREAD

**Issue by sowd** [Hiroshi-Sugimura/echonet-lite.js#6]
The new version shows the following warning:

(node:8254) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by sowd** [comment]
I saw the code and found that just replacing 'new Buffer' by 'Buffer.from' is sufficient to remove this issue. Buffer.from() is so vulnerable that it will be backported down to node v4.

Source(JP) : https://techblog.yahoo.co.jp/advent-calendar-2016/node_new_buffer/

Could you do it?

**Comment by Hiroshi-Sugimura** [comment]
done.
