### ISSUE TITLE
プロパティ値の自動問い合わせを無効化するオプション

### ISSUE THREAD

**Issue by sowd** [Hiroshi-Sugimura/echonet-lite.js#8]
IssueではなくRequestです。

プロパティマップを受け取ると、そこに含まれる値を200ms間隔で自動的に問い合わせるようになっているようですが、相手が非力だと対処しきれない可能性もあるので、この問い合わせをdisableできる設定を追加して頂けませんでしょうか？

**Comment by Hiroshi-Sugimura** [comment]
trialでautoGetPropertiesオプションを追加しました。default trueです。これをfalseに指定してみてください。

EL.initialize = function ( objList, userfunc, ipVer = 4, Options = {v4: '', v6: '', ignoreMe: false, autoGetProperties: true} )

プロパティマップは取得しますが，各プロパティは取得しないように止めるフラグです。

**Comment by sowd** [comment]
すみません、気づいていませんでした。即対応ありがとうございます！！

**Comment by sowd** [comment]
オプション設定しても聞きに行っているようです。
もう一度ご確認いただけますか？
