### ISSUE TITLE
EL.parseBytes()での複数OPCの場合

### ISSUE THREAD

**Issue by ryoma3111** [Hiroshi-Sugimura/echonet-lite.js#9]
EL.parseBytes()を使用してOPCが2以上のデータを受信する際、edtデータが結合された形式で出力されます。
{"80":"31","b0":"3142","bb":"31421c","b3":"31421c18"}
これはエアコンの設定情報を複数読み出し要求した際の返答データです。

**Comment by Hiroshi-Sugimura** [comment]
問題の再現を確認しました。修正します。

**Comment by ryoma3111** [comment]
よろしくお願いします

**Comment by Hiroshi-Sugimura** [comment]
修正しました。
v2.4.1です。お試しください。

**Comment by ryoma3111** [comment]
ありがとうございます。
早速アップデートしてみます。

**Comment by ryoma3111** [comment]
もう一つ改良をお願いします。
エアコンに対象プロパティのESV:63状態変化通知要求を送信した後、状態変化時の通知ESV:73を受信しました。
データのプロパティが多く上記問題と同じようにDETAILsに溜まります。
